### PR TITLE
Added easy-to-use interface and instructions

### PR DESCRIPTION
**Pull request by kevinejohn**

### CODE REVIEW

**Comment by awitherow** [comment]
Hello @kevinejohn @vnil why has this not been merged?

**Comment by awitherow** [comment]
also @vnil @kevinejohn is this thing up to date with the latest react native dependencies?

**Comment by kevinejohn** [comment]
I would like to get this merged but I haven't heard anything from @vnil . I assume this still works with the latest version of RN

**Comment by awitherow** [comment]
Nice @kevinejohn, well let's hope that if we continuously ping @vnil he will show up soon 😄 

Are @kevinejohn are you using this in production?

**Comment by vnil** [comment]
Hi @kevinejohn @awitherow! Sorry about not being active, was mostly for a private project but glad to see you found interest in this! I'll try to get an updated version to npm sometime during the day! I can't confirm if the code base is up to date with the latest version of RN. I'll write again when I have had time to look at this!

**Comment by awitherow** [comment]
very nice @kevinejohn @vnil ! 🎉

**Comment by vnil** [comment]
Alrighty, should be on npm now. Changed the version to 1.0.0 since it was a breaking change.

**Pull request merged**
